### ISSUE TITLE
Help debugging, meaningless error message 

### ISSUE THREAD

**Issue by galinyc1** [altaurog/pgcopy#31] opened 2022-09-01 13:18 UTC
Thank you for all the help, I'm using your solution all the time! 

My code fails in the current project on the following line (worked in many other projects): 
worker.copy(row, BytesIO)

And the error that I get is:
ERROR: Something went wrong with XXXXXX table.

I tried reviewing all the code and PostgreSQL logs and I can't find anything.

Any recommendation, where or what to look for?

Thanks!

**Comment by altaurog** [comment] 2022-09-04 08:28
Thanks for your interest in pgcopy!  I am glad this library has been useful for you.

Can you provide a traceback?  This error is indeed quite vague.

Can you eliminate the possibility of a data-related issue by trying with only one row?  If you can get it to work for one row, can you identify specific rows/values that are problematic?  I implemented once a sort of binary search that broke the data set up into successively smaller segments, running copy on each one until failing segments were all reduced to a single row, but that would only be useful if you are certain the problem is with the data (and you have a very large data set).

**Comment by galinyc1** [comment] 2022-09-06 19:09
I did so much debugging, sorry for the delay. 
I think I found the problem 
When querying the data and getting the output from deepcopy, I'm getting 6 figures for the milliseconds' value in a date column. 
Since milliseconds should be between 0-999.
Source data type is timestamp
Target data type is timestamp

And I'm getting values like:
datetime.datetime(2022, 9, 6, 19, 3, 40, 209000)

To be inserted in the target.

Thank you again!

**Comment by altaurog** [comment] 2022-09-06 19:54
Thanks for the update, @galinyc1 .  Just curious, where was the error raised?

**Comment by altaurog** [comment] 2022-09-07 07:34
That’s the error, which you sent.  Where in the code was this raised?  Can you send me a traceback?

**Comment by galinyc1** [comment] 2022-09-07 18:06
Sorry, I did more debugging and it was my fault. 
The problem was actually that target data type was NUMERIC and I have to convert the data in python to Decimel to get it working. 

To my original request in this issue, I don't know how to produce a traceback.

**Comment by altaurog** [comment] 2022-09-08 10:43
In any case, I am glad you found the solution!  I’m closing this issue, feel free to re-open it if necessary.

**Closed as completed by altaurog** 2022-09-08 10:43 UTC
